### ISSUE TITLE
Broken Forge 1.20 download link

### ISSUE THREAD

**Issue by mpustovoi** [CelestiumMC/abridged#1]
Not a mod itself bug.
The Forge 1.20 version cannot be added to the Modrinth custom modpack. Perhaps because of two identical files for downloading, idk. You have to download it from the site manually. Thus, there will be no auto-update function available:
![image](https://github.com/CelestiumMC/abridged/assets/92390626/ed261a7b-f4b6-40da-a4d8-b1a8ffcfd0de)
This error appears:
![image](https://github.com/CelestiumMC/abridged/assets/92390626/735c42ee-fd61-4ae9-a28f-359920f558ab)
It says that the mod is installed, but it actually isn't. Afterwards, I just can't find it in the modpack mod list or in mods directory.
Btw, the Fabric 1.20 version is installed absolutely fine, probably due to the absence of a duplicate file.

**Comment by Apollounknowndev** [comment]
Fixed the 1.0.0 release. Just pushed the 1.1.0 release and it didn't occur, so I have no clue how it originally happened.
